version: '3.8'

services:
  app:
    container_name: backend-notas
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app  
  mongo:
    container_name: mongodb-notas
    image: mongo
    ports:
      - "27017:27017"  
